### ISSUE TITLE
Не находит город

### ISSUE THREAD

**Issue by acnapd** [lers-uchet/ImportTemperatureMeteoInfo#1]
Предположительно из за неверной ссылки '**http**://meteoinfo.ru/archive-pogoda/russia/moscow'
должна быть '**https**://meteoinfo.ru/archive-pogoda/russia/moscow'

**Comment by achikhv** [comment]
Кроме https ещё поменялась разметка страниц, поэтому модуль сейчас не работает.

**Comment by acnapd** [comment]
планируете восстанавливать?

**Comment by Werzet** [comment]
Работа утилиты восстановлена.
